alsa_CFLAGS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --cflags alsa)
alsa_LDFLAGS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs-only-L alsa)
alsa_LDLIBS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs-only-l --libs-only-other alsa)

SPOTFLAGS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --cflags libspotify) $(alsa_CFLAGS)
LDFLAGS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs-only-L libspotify) $(alsa_LDFLAGS)
LDLIBS = $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs-only-l --libs-only-other libspotify) $(alsa_LDLIBS)

SUBLIBS = -lspotify -lasound -lsndfile

#############################################################################
# Makefile for building: juniper
# Generated by qmake (2.01a) (Qt 4.5.0) on: Mon Aug 17 20:00:05 2009
# Project:  juniper.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile juniper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = $(SPOTFLAGS) -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = $(SPOTFLAGS) -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = alsaworker.cpp \
		appkey.c \
		main.cpp \
		mainwindow.cpp \
		qlistlistmodel.cpp \
		qlistlistview.cpp \
		qplaylistmodel.cpp \
		qplaylistview.cpp \
		qsearchlistmodel.cpp \
		soundsaver.cpp \
		spotworker.cpp moc_alsaworker.cpp \
		moc_mainwindow.cpp \
		moc_qlistlistmodel.cpp \
		moc_qlistlistview.cpp \
		moc_qplaylistmodel.cpp \
		moc_qplaylistview.cpp \
		moc_qsearchlistmodel.cpp \
		moc_soundsaver.cpp \
		moc_spotworker.cpp
OBJECTS       = alsaworker.o \
		appkey.o \
		main.o \
		mainwindow.o \
		qlistlistmodel.o \
		qlistlistview.o \
		qplaylistmodel.o \
		qplaylistview.o \
		qsearchlistmodel.o \
		soundsaver.o \
		spotworker.o \
		moc_alsaworker.o \
		moc_mainwindow.o \
		moc_qlistlistmodel.o \
		moc_qlistlistview.o \
		moc_qplaylistmodel.o \
		moc_qplaylistview.o \
		moc_qsearchlistmodel.o \
		moc_soundsaver.o \
		moc_spotworker.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		juniper.pro
QMAKE_TARGET  = juniper
DESTDIR       = 
TARGET        = juniper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: juniper.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile juniper.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile juniper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/juniper1.0.0 || $(MKDIR) .tmp/juniper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/juniper1.0.0/ && $(COPY_FILE) --parents alsaworker.hpp mainwindow.hpp qlistlistmodel.hpp qlistlistview.hpp qplaylistmodel.hpp qplaylistview.hpp qsearchlistmodel.hpp queue.h soundsaver.hpp spotworker.hpp .tmp/juniper1.0.0/ && $(COPY_FILE) --parents alsaworker.cpp appkey.c main.cpp mainwindow.cpp qlistlistmodel.cpp qlistlistview.cpp qplaylistmodel.cpp qplaylistview.cpp qsearchlistmodel.cpp soundsaver.cpp spotworker.cpp .tmp/juniper1.0.0/ && (cd `dirname .tmp/juniper1.0.0` && $(TAR) juniper1.0.0.tar juniper1.0.0 && $(COMPRESS) juniper1.0.0.tar) && $(MOVE) `dirname .tmp/juniper1.0.0`/juniper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/juniper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_alsaworker.cpp moc_mainwindow.cpp moc_qlistlistmodel.cpp moc_qlistlistview.cpp moc_qplaylistmodel.cpp moc_qplaylistview.cpp moc_qsearchlistmodel.cpp moc_soundsaver.cpp moc_spotworker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_alsaworker.cpp moc_mainwindow.cpp moc_qlistlistmodel.cpp moc_qlistlistview.cpp moc_qplaylistmodel.cpp moc_qplaylistview.cpp moc_qsearchlistmodel.cpp moc_soundsaver.cpp moc_spotworker.cpp
moc_alsaworker.cpp: queue.h \
		soundsaver.hpp \
		alsaworker.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) alsaworker.hpp -o moc_alsaworker.cpp

moc_mainwindow.cpp: spotworker.hpp \
		alsaworker.hpp \
		queue.h \
		soundsaver.hpp \
		qlistlistview.hpp \
		qlistlistmodel.hpp \
		qplaylistview.hpp \
		qplaylistmodel.hpp \
		qsearchlistmodel.hpp \
		mainwindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.hpp -o moc_mainwindow.cpp

moc_qlistlistmodel.cpp: qlistlistmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qlistlistmodel.hpp -o moc_qlistlistmodel.cpp

moc_qlistlistview.cpp: qlistlistview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qlistlistview.hpp -o moc_qlistlistview.cpp

moc_qplaylistmodel.cpp: qplaylistmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qplaylistmodel.hpp -o moc_qplaylistmodel.cpp

moc_qplaylistview.cpp: qplaylistview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qplaylistview.hpp -o moc_qplaylistview.cpp

moc_qsearchlistmodel.cpp: qsearchlistmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qsearchlistmodel.hpp -o moc_qsearchlistmodel.cpp

moc_soundsaver.cpp: soundsaver.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) soundsaver.hpp -o moc_soundsaver.cpp

moc_spotworker.cpp: alsaworker.hpp \
		queue.h \
		soundsaver.hpp \
		spotworker.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spotworker.hpp -o moc_spotworker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

alsaworker.o: alsaworker.cpp queue.h \
		alsaworker.hpp \
		soundsaver.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alsaworker.o alsaworker.cpp

appkey.o: appkey.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o appkey.o appkey.c

main.o: main.cpp mainwindow.hpp \
		spotworker.hpp \
		alsaworker.hpp \
		queue.h \
		soundsaver.hpp \
		qlistlistview.hpp \
		qlistlistmodel.hpp \
		qplaylistview.hpp \
		qplaylistmodel.hpp \
		qsearchlistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hpp \
		spotworker.hpp \
		alsaworker.hpp \
		queue.h \
		soundsaver.hpp \
		qlistlistview.hpp \
		qlistlistmodel.hpp \
		qplaylistview.hpp \
		qplaylistmodel.hpp \
		qsearchlistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qlistlistmodel.o: qlistlistmodel.cpp qlistlistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qlistlistmodel.o qlistlistmodel.cpp

qlistlistview.o: qlistlistview.cpp qlistlistview.hpp \
		qlistlistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qlistlistview.o qlistlistview.cpp

qplaylistmodel.o: qplaylistmodel.cpp qplaylistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qplaylistmodel.o qplaylistmodel.cpp

qplaylistview.o: qplaylistview.cpp qplaylistview.hpp \
		qplaylistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qplaylistview.o qplaylistview.cpp

qsearchlistmodel.o: qsearchlistmodel.cpp qsearchlistmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsearchlistmodel.o qsearchlistmodel.cpp

soundsaver.o: soundsaver.cpp soundsaver.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundsaver.o soundsaver.cpp

spotworker.o: spotworker.cpp spotworker.hpp \
		alsaworker.hpp \
		queue.h \
		soundsaver.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spotworker.o spotworker.cpp

moc_alsaworker.o: moc_alsaworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alsaworker.o moc_alsaworker.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qlistlistmodel.o: moc_qlistlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qlistlistmodel.o moc_qlistlistmodel.cpp

moc_qlistlistview.o: moc_qlistlistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qlistlistview.o moc_qlistlistview.cpp

moc_qplaylistmodel.o: moc_qplaylistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qplaylistmodel.o moc_qplaylistmodel.cpp

moc_qplaylistview.o: moc_qplaylistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qplaylistview.o moc_qplaylistview.cpp

moc_qsearchlistmodel.o: moc_qsearchlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsearchlistmodel.o moc_qsearchlistmodel.cpp

moc_soundsaver.o: moc_soundsaver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundsaver.o moc_soundsaver.cpp

moc_spotworker.o: moc_spotworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spotworker.o moc_spotworker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

